define(['handlebars.runtime'], function(Handlebars) {

return Handlebars.template({"1":function(depth0,helpers,partials,data) {
    var helper, alias1=helpers.helperMissing, alias2="function", alias3=this.escapeExpression;

  return "						<option value=\""
    + alias3(((helper = (helper = helpers.id || (depth0 != null ? depth0.id : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"id","hash":{},"data":data}) : helper)))
    + "\">"
    + alias3(((helper = (helper = helpers.name || (depth0 != null ? depth0.name : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"name","hash":{},"data":data}) : helper)))
    + "</option>\r\n";
},"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
    var stack1, helper, alias1=helpers.helperMissing, alias2="function", alias3=this.escapeExpression;

  return "<div id=\"rc-app\" class=\"rc-app rc-app-reset\">\r\n	<form name=\"rcAppForm\" action=\"http://www.rentalcars.com/LoadingSearchResults.do\" target=\"_blank\">\r\n		<input type=\"hidden\" name=\"affiliateCode\">\r\n		<input type=\"hidden\" name=\"puSameAsDo\" value=\"false\">\r\n		<input type=\"hidden\" name=\"emptySearchResults\" value=\"true\">\r\n		<input type=\"hidden\" name=\"locationName\">\r\n		<input type=\"hidden\" name=\"dropLocationName\">\r\n		<h3>"
    + alias3(((helper = (helper = helpers.title || (depth0 != null ? depth0.title : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"title","hash":{},"data":data}) : helper)))
    + "</h3>\r\n		<div class=\"rc-form-group-wrap rc-form-group-wrap--locations rc-form-group-wrap--pickup\">\r\n			<div class=\"rc-form-group rc-form-group--country\">\r\n				<label>"
    + alias3(((helper = (helper = helpers.country || (depth0 != null ? depth0.country : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"country","hash":{},"data":data}) : helper)))
    + "</label>\r\n				<select class=\"rc-form-control rc-form-control--country\" name=\"country\" onchange=\"rcApp.localeChanged(this)\">\r\n					<option selected=\"selected\" disabled=\"disabled\" value=\"0\">"
    + alias3(((helper = (helper = helpers.emptySelect || (depth0 != null ? depth0.emptySelect : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"emptySelect","hash":{},"data":data}) : helper)))
    + "</option>\r\n"
    + ((stack1 = helpers.each.call(depth0,(depth0 != null ? depth0.countries : depth0),{"name":"each","hash":{},"fn":this.program(1, data, 0),"inverse":this.noop,"data":data})) != null ? stack1 : "")
    + "				</select>\r\n			</div>\r\n			<div class=\"rc-form-group rc-form-group--city\">\r\n				<label>"
    + alias3(((helper = (helper = helpers.city || (depth0 != null ? depth0.city : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"city","hash":{},"data":data}) : helper)))
    + "</label>\r\n				<select disabled=\"disabled\" class=\"rc-form-control rc-form-control--city\" name=\"city\" onchange=\"rcApp.localeChanged(this)\">\r\n					<option selected=\"selected\" disabled=\"disabled\" value=\"0\">"
    + alias3(((helper = (helper = helpers.emptySelect || (depth0 != null ? depth0.emptySelect : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"emptySelect","hash":{},"data":data}) : helper)))
    + "</option>\r\n				</select>\r\n			</div>\r\n			<div class=\"rc-form-group rc-form-group--location\">\r\n				<label>"
    + alias3(((helper = (helper = helpers.location || (depth0 != null ? depth0.location : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"location","hash":{},"data":data}) : helper)))
    + "</label>\r\n				<select disabled=\"disabled\" class=\"rc-form-control rc-form-control--location\" name=\"location\" onchange=\"rcApp.localeChanged(this)\">\r\n					<option selected=\"selected\" disabled=\"disabled\" value=\"0\">"
    + alias3(((helper = (helper = helpers.emptySelect || (depth0 != null ? depth0.emptySelect : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"emptySelect","hash":{},"data":data}) : helper)))
    + "</option>\r\n				</select>\r\n			</div>\r\n		</div>\r\n		<div class=\"rc-form-group-wrap rc-form-group-wrap--locations rc-form-group-wrap--dropoff\" id=\"rc-dropoff\">\r\n			<h4>"
    + alias3(((helper = (helper = helpers.dropOff || (depth0 != null ? depth0.dropOff : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"dropOff","hash":{},"data":data}) : helper)))
    + "</h4>\r\n			<div class=\"rc-form-group rc-form-group--drop-country\">\r\n				<label>"
    + alias3(((helper = (helper = helpers.country || (depth0 != null ? depth0.country : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"country","hash":{},"data":data}) : helper)))
    + "</label>\r\n				<select disabled=\"disabled\" class=\"rc-form-control rc-form-control--country\" name=\"dropCountry\" onchange=\"rcApp.localeChanged(this)\">\r\n					<option selected=\"selected\" disabled=\"disabled\" value=\"0\">"
    + alias3(((helper = (helper = helpers.emptySelect || (depth0 != null ? depth0.emptySelect : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"emptySelect","hash":{},"data":data}) : helper)))
    + "</option>\r\n				</select>\r\n			</div>\r\n			<div class=\"rc-form-group rc-form-group--drop-country\">\r\n				<label>"
    + alias3(((helper = (helper = helpers.city || (depth0 != null ? depth0.city : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"city","hash":{},"data":data}) : helper)))
    + "</label>\r\n				<select disabled=\"disabled\" class=\"rc-form-control rc-form-control--city\" name=\"dropCity\" onchange=\"rcApp.localeChanged(this)\">\r\n					<option selected=\"selected\" disabled=\"disabled\" value=\"0\">"
    + alias3(((helper = (helper = helpers.emptySelect || (depth0 != null ? depth0.emptySelect : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"emptySelect","hash":{},"data":data}) : helper)))
    + "</option>\r\n				</select>\r\n			</div>\r\n			<div class=\"rc-form-group rc-form-group--drop-country\">\r\n				<label>"
    + alias3(((helper = (helper = helpers.location || (depth0 != null ? depth0.location : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"location","hash":{},"data":data}) : helper)))
    + "</label>\r\n				<select disabled=\"disabled\" class=\"rc-form-control rc-form-control--location\" name=\"dropLocation\" onchange=\"rcApp.dropLocationChanged()\">\r\n					<option selected=\"selected\" disabled=\"disabled\" value=\"0\">"
    + alias3(((helper = (helper = helpers.emptySelect || (depth0 != null ? depth0.emptySelect : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"emptySelect","hash":{},"data":data}) : helper)))
    + "</option>\r\n				</select>\r\n			</div>\r\n		</div>\r\n		<div class=\"rc-form-group rc-form-group--return\">\r\n			<label><input type=\"checkbox\" checked=\"checked\" onchange=\"rcApp.returnChanged(this)\">"
    + alias3(((helper = (helper = helpers.returnSameLocation || (depth0 != null ? depth0.returnSameLocation : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"returnSameLocation","hash":{},"data":data}) : helper)))
    + "</label>\r\n		</div>\r\n		<div class=\"rc-form-group rc-form-group--date rc-date--pickup\">\r\n			<label>"
    + alias3(((helper = (helper = helpers.pickUpDate || (depth0 != null ? depth0.pickUpDate : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"pickUpDate","hash":{},"data":data}) : helper)))
    + "</label>\r\n			<input class=\"rc-form-control rc-form-control--date\" readonly=\"readonly\" spellcheck=\"false\" type=\"text\" name=\"\" id=\"rc-datepicker--pickup\">\r\n			<input type=\"hidden\" name=\"puDay\">\r\n			<input type=\"hidden\" name=\"puMonth\">\r\n			<input type=\"hidden\" name=\"puYear\">\r\n		</div>\r\n		<div class=\"rc-form-group rc-form-group--time rc-time--pickup\">\r\n			<label>"
    + alias3(((helper = (helper = helpers.time || (depth0 != null ? depth0.time : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"time","hash":{},"data":data}) : helper)))
    + "</label>\r\n			<div class=\"rc-form-control-wrap rc-form-control-wrap--time\">\r\n				<select class=\"rc-form-control rc-form-control--hour\" name=\"puHour\">\r\n					<option value=\"00\">00</option>\r\n					<option value=\"01\">01</option>\r\n					<option value=\"02\">02</option>\r\n					<option value=\"03\">03</option>\r\n					<option value=\"04\">04</option>\r\n					<option value=\"05\">05</option>\r\n					<option value=\"06\">06</option>\r\n					<option value=\"07\">07</option>\r\n					<option value=\"08\">08</option>\r\n					<option value=\"09\">09</option>\r\n					<option value=\"10\" selected=\"selected\">10</option>\r\n					<option value=\"11\">11</option>\r\n					<option value=\"12\">12</option>\r\n					<option value=\"13\">13</option>\r\n					<option value=\"14\">14</option>\r\n					<option value=\"15\">15</option>\r\n					<option value=\"16\">16</option>\r\n					<option value=\"17\">17</option>\r\n					<option value=\"18\">18</option>\r\n					<option value=\"19\">19</option>\r\n					<option value=\"20\">20</option>\r\n					<option value=\"21\">21</option>\r\n					<option value=\"22\">22</option>\r\n					<option value=\"23\">23</option>\r\n				</select>\r\n				<select class=\"rc-form-control rc-form-control--minute\" name=\"puMinute\">\r\n					<option value=\"00\">00</option>\r\n					<option value=\"15\">15</option>\r\n					<option value=\"30\" selected=\"selected\">30</option>\r\n					<option value=\"45\">45</option>\r\n				</select>\r\n			</div>\r\n		</div>\r\n		<div class=\"rc-form-group rc-form-group--date rc-date--dropoff\">\r\n			<label>"
    + alias3(((helper = (helper = helpers.dropOffDate || (depth0 != null ? depth0.dropOffDate : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"dropOffDate","hash":{},"data":data}) : helper)))
    + "</label>\r\n			<input class=\"rc-form-control rc-form-control--date\" readonly=\"readonly\" spellcheck=\"false\" type=\"text\" name=\"\" id=\"rc-datepicker--dropoff\">\r\n			<input type=\"hidden\" name=\"doDay\">\r\n			<input type=\"hidden\" name=\"doMonth\">\r\n			<input type=\"hidden\" name=\"doYear\">\r\n		</div>\r\n		<div class=\"rc-form-group rc-form-group--time rc-time--pickup\">\r\n			<label>"
    + alias3(((helper = (helper = helpers.time || (depth0 != null ? depth0.time : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"time","hash":{},"data":data}) : helper)))
    + "</label>\r\n			<div class=\"rc-form-control-wrap rc-form-control-wrap--time\">\r\n				<select class=\"rc-form-control rc-form-control--hour\" name=\"doHour\">\r\n					<option value=\"00\">00</option>\r\n					<option value=\"01\">01</option>\r\n					<option value=\"02\">02</option>\r\n					<option value=\"03\">03</option>\r\n					<option value=\"04\">04</option>\r\n					<option value=\"05\">05</option>\r\n					<option value=\"06\">06</option>\r\n					<option value=\"07\">07</option>\r\n					<option value=\"08\">08</option>\r\n					<option value=\"09\">09</option>\r\n					<option value=\"10\" selected=\"selected\">10</option>\r\n					<option value=\"11\">11</option>\r\n					<option value=\"12\">12</option>\r\n					<option value=\"13\">13</option>\r\n					<option value=\"14\">14</option>\r\n					<option value=\"15\">15</option>\r\n					<option value=\"16\">16</option>\r\n					<option value=\"17\">17</option>\r\n					<option value=\"18\">18</option>\r\n					<option value=\"19\">19</option>\r\n					<option value=\"20\">20</option>\r\n					<option value=\"21\">21</option>\r\n					<option value=\"22\">22</option>\r\n					<option value=\"23\">23</option>\r\n				</select>\r\n				<select class=\"rc-form-control rc-form-control--minute\" name=\"doMinute\">\r\n					<option value=\"00\">00</option>\r\n					<option value=\"15\">15</option>\r\n					<option value=\"30\" selected=\"selected\">30</option>\r\n					<option value=\"45\">45</option>\r\n				</select>\r\n			</div>\r\n		</div>\r\n		<div class=\"rc-form-group rc-form-group--age\">\r\n			<label>"
    + alias3(((helper = (helper = helpers.driverAge || (depth0 != null ? depth0.driverAge : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"driverAge","hash":{},"data":data}) : helper)))
    + "</label>\r\n			<input class=\"rc-form-control rc-form-control--age\" value=\"25\" type=\"text\" name=\"driversAge\">\r\n		</div>\r\n		<div class=\"rc-form-group rc-form-group--submit\">\r\n			<button class=\"rc-button\">"
    + alias3(((helper = (helper = helpers.search || (depth0 != null ? depth0.search : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"search","hash":{},"data":data}) : helper)))
    + "</button>\r\n		</div>\r\n	</form>\r\n</div>";
},"useData":true})

});