define(['handlebars.runtime'], function(Handlebars) {

return Handlebars.template({"1":function(depth0,helpers,partials,data) {
    var helper, alias1=helpers.helperMissing, alias2="function", alias3=this.escapeExpression;

  return "					<option value=\""
    + alias3(((helper = (helper = helpers.value || (depth0 != null ? depth0.value : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"value","hash":{},"data":data}) : helper)))
    + "\">"
    + alias3(((helper = (helper = helpers.name || (depth0 != null ? depth0.name : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"name","hash":{},"data":data}) : helper)))
    + "</option>\r\n";
},"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
    var stack1, helper, alias1=helpers.helperMissing, alias2="function", alias3=this.escapeExpression;

  return "<div class=\"rc-app\">\r\n	<form name=\"rcAppForm\" action=\"http://www.rentalcars.com\" target=\"_blank\">\r\n		<p class=\"rc-title\">"
    + alias3(((helper = (helper = helpers.title || (depth0 != null ? depth0.title : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"title","hash":{},"data":data}) : helper)))
    + "</p>\r\n		<div class=\"rc-form-group rc-locations rc-locations--pickup\">\r\n			<select class=\"rc-location rc-location--country\" name=\"country\">\r\n				<option selected=\"selected\" disabled=\"disabled\" value=\"0\">"
    + alias3(((helper = (helper = helpers.country || (depth0 != null ? depth0.country : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"country","hash":{},"data":data}) : helper)))
    + "</option>\r\n"
    + ((stack1 = helpers.each.call(depth0,(depth0 != null ? depth0.countries : depth0),{"name":"each","hash":{},"fn":this.program(1, data, 0),"inverse":this.noop,"data":data})) != null ? stack1 : "")
    + "			</select>\r\n			<select class=\"rc-location rc-location--city\" name=\"city\">\r\n				<option selected=\"selected\" disabled=\"disabled\" value=\"0\">"
    + alias3(((helper = (helper = helpers.city || (depth0 != null ? depth0.city : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"city","hash":{},"data":data}) : helper)))
    + "</option>\r\n			</select>\r\n			<select class=\"rc-location rc-location--location\" name=\"location\">\r\n				<option selected=\"selected\" disabled=\"disabled\" value=\"0\">"
    + alias3(((helper = (helper = helpers.location || (depth0 != null ? depth0.location : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"location","hash":{},"data":data}) : helper)))
    + "</option>\r\n			</select>\r\n		</div>\r\n		<div class=\"rc-form-group rc-locations rc-locations--dropoff\">\r\n			<select class=\"rc-location rc-location--country\" name=\"country\">\r\n				<option selected=\"selected\" disabled=\"disabled\" value=\"0\">"
    + alias3(((helper = (helper = helpers.country || (depth0 != null ? depth0.country : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"country","hash":{},"data":data}) : helper)))
    + "</option>\r\n			</select>\r\n			<select class=\"rc-location rc-location--city\" name=\"city\">\r\n				<option selected=\"selected\" disabled=\"disabled\" value=\"0\">"
    + alias3(((helper = (helper = helpers.city || (depth0 != null ? depth0.city : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"city","hash":{},"data":data}) : helper)))
    + "</option>\r\n			</select>\r\n			<select class=\"rc-location rc-location--location\" name=\"location\">\r\n				<option selected=\"selected\" disabled=\"disabled\" value=\"0\">"
    + alias3(((helper = (helper = helpers.location || (depth0 != null ? depth0.location : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"location","hash":{},"data":data}) : helper)))
    + "</option>\r\n			</select>\r\n		</div>\r\n		<div class=\"rc-form-group rc-date rc-date--pickup\">\r\n			<label for=\"rc-datepicker--pickup\">"
    + alias3(((helper = (helper = helpers.pickupDate || (depth0 != null ? depth0.pickupDate : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"pickupDate","hash":{},"data":data}) : helper)))
    + "</label>\r\n			<input spellcheck=\"false\" type=\"text\" name=\"\" id=\"rc-datepicker--pickup\">\r\n			<input type=\"hidden\" name=\"puDay\">\r\n			<input type=\"hidden\" name=\"puMonth\">\r\n			<input type=\"hidden\" name=\"puYear\">\r\n		</div>\r\n		<div class=\"rc-form-group rc-time rc-time--pickup\">\r\n			<select class=\"rc-hour\" name=\"puHour\">\r\n				<option value=\"00\">00</option>\r\n				<option value=\"01\">01</option>\r\n				<option value=\"02\">02</option>\r\n				<option value=\"03\">03</option>\r\n				<option value=\"04\">04</option>\r\n				<option value=\"05\">05</option>\r\n				<option value=\"06\">06</option>\r\n				<option value=\"07\">07</option>\r\n				<option value=\"08\">08</option>\r\n				<option value=\"09\">09</option>\r\n				<option value=\"10\" selected=\"selected\">10</option>\r\n				<option value=\"11\">11</option>\r\n				<option value=\"12\">12</option>\r\n				<option value=\"13\">13</option>\r\n				<option value=\"14\">14</option>\r\n				<option value=\"15\">15</option>\r\n				<option value=\"16\">16</option>\r\n				<option value=\"17\">17</option>\r\n				<option value=\"18\">18</option>\r\n				<option value=\"19\">19</option>\r\n				<option value=\"20\">20</option>\r\n				<option value=\"21\">21</option>\r\n				<option value=\"22\">22</option>\r\n				<option value=\"23\">23</option>\r\n			</select>\r\n			<select class=\"rc-minute\" name=\"puMinute\">\r\n				<option value=\"00\">00</option>\r\n				<option value=\"15\">15</option>\r\n				<option value=\"30\" selected=\"selected\">30</option>\r\n				<option value=\"45\">45</option>\r\n			</select>\r\n		</div>\r\n		<div class=\"rc-form-group rc-date rc-date--dropoff\">\r\n			<label for=\"rc-datepicker--dropoff\">"
    + alias3(((helper = (helper = helpers.dropoffDate || (depth0 != null ? depth0.dropoffDate : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"dropoffDate","hash":{},"data":data}) : helper)))
    + "</label>\r\n			<input spellcheck=\"false\" type=\"text\" name=\"\" id=\"rc-datepicker--dropoff\">\r\n			<input type=\"hidden\" name=\"doDay\">\r\n			<input type=\"hidden\" name=\"doMonth\">\r\n			<input type=\"hidden\" name=\"doYear\">\r\n		</div>\r\n		<div class=\"rc-form-group rc-time rc-time--pickup\">\r\n			<select class=\"rc-hour\" name=\"doHour\">\r\n				<option value=\"00\">00</option>\r\n				<option value=\"01\">01</option>\r\n				<option value=\"02\">02</option>\r\n				<option value=\"03\">03</option>\r\n				<option value=\"04\">04</option>\r\n				<option value=\"05\">05</option>\r\n				<option value=\"06\">06</option>\r\n				<option value=\"07\">07</option>\r\n				<option value=\"08\">08</option>\r\n				<option value=\"09\">09</option>\r\n				<option value=\"10\" selected=\"selected\">10</option>\r\n				<option value=\"11\">11</option>\r\n				<option value=\"12\">12</option>\r\n				<option value=\"13\">13</option>\r\n				<option value=\"14\">14</option>\r\n				<option value=\"15\">15</option>\r\n				<option value=\"16\">16</option>\r\n				<option value=\"17\">17</option>\r\n				<option value=\"18\">18</option>\r\n				<option value=\"19\">19</option>\r\n				<option value=\"20\">20</option>\r\n				<option value=\"21\">21</option>\r\n				<option value=\"22\">22</option>\r\n				<option value=\"23\">23</option>\r\n			</select>\r\n			<select class=\"rc-minute\" name=\"doMinute\">\r\n				<option value=\"00\">00</option>\r\n				<option value=\"15\">15</option>\r\n				<option value=\"30\" selected=\"selected\">30</option>\r\n				<option value=\"45\">45</option>\r\n			</select>\r\n		</div>\r\n		<div class=\"rc-form-group rc-submit\">\r\n			<button class=\"rc-submit__button\">"
    + alias3(((helper = (helper = helpers.submit || (depth0 != null ? depth0.submit : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"submit","hash":{},"data":data}) : helper)))
    + "</button>\r\n		</div>\r\n	</form>\r\n</div>";
},"useData":true})

});